language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
node_js:
- stable
script:
- npm test
before_deploy:
- npm run release
deploy:
  provider: npm
  email: dovydas@quatrodev.com
  api_key: $SIMPLR_NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    repo: SimplrJS/simplr-dropdown
